apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readpods
  namespace: saumya
subjects:
- kind: ServiceAccount
  name: demo
  namespace: saumya
roleRef:
  kind: Role
  name: podreader
  apiGroup: rbac.authorization.k8s.io
